### ISSUE TITLE
PeakFitterMrqdt commit somehow reintroduced and old bug with setting NDF

### ISSUE THREAD

**Issue by SFBayLaser** [LArSoft/larreco#30]
https://github.com/LArSoft/larreco/commits/develop/larreco/HitFinder/HitFinderTools/PeakFitterMrqdt_tool.cc

See the above, it seems when I click on the "clang format" link from May 20 that a bug in the calculation of NDF is reintroduced into the code... specifically at line 125 of https://github.com/LArSoft/larreco/blob/develop/larreco/HitFinder/HitFinderTools/PeakFitterMrqdt_tool.cc you can see that it tries to set the value of a local version of NDF, not the global one... 

This was originally fixed by Giuseppe a long time ago... as our tracking is now working with data in ICARUS we are using NDF to separate out "long hits" and did not understand why all hits at the value of 1... 

I think this is a simple fix, can it be done for this week's release?

**Comment by knoepfel** [comment]
Tracy, I see that you added the bugfix to PR #29.  Can you create a separate PR with the one bugfix?  It will be much easier to include it in this week's release.
